sci = scientific , py = python   
## means the scientific computation in python
## it is created by Travis olliphant who created numpy also
## far more useful because it handle complex problems like we can find the solution of linear equation from numpy    but it solves non li ear also like x + cos(x)
## mostly written in python but some segments are written in c 

In [2]:
import scipy
print(scipy.__version__)

1.15.2


In [5]:
## constants
from scipy import constants
print(constants.kilo)
print(constants.deci)
print(constants.hecto)
print(constants.gibi)
print(constants.torr)
print(constants.degree_Fahrenheit)
print(constants.hectare)
print(constants.minute)
print(constants.dyne)
print(constants.ounce)
print(constants.barrel)
print(constants.mph)
print(constants.calorie)
print(constants.mega)
print(constants.tebi)


1000.0
0.1
100.0
1073741824
133.32236842105263
0.5555555555555556
10000.0
60.0
1e-05
0.028349523124999998
0.15898729492799998
0.44703999999999994
4.184
1000000.0
1099511627776


## optimizers = use to find root for non linear,linear equation and helpful for minimze the data

In [ ]:
## optimizers
from scipy.optimize import root
from math import cos
def eqn(x):
    return x + cos(x)
my_root = root(eqn,0)
print(my_root)
print()
print(my_root.x)        ## .x because we want only result not the various calculation inside the solution

 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00]
       x: [-7.391e-01]
  method: hybr
    nfev: 11
    fjac: [[-1.000e+00]]
       r: [-1.674e+00]
     qtf: [-2.668e-13]

[-0.73908513]


C:\Users\hp\AppData\Local\Temp\ipykernel_7944\1837421043.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return x + cos(x)


In [14]:
## minimize
from scipy.optimize import minimize
def eqn(x):
    return x**2 + x + 2
my_min = minimize(eqn,0,method = 'BFGS')    ## single quotes always
print(my_min)
print()
print(my_min.x)

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 1.75
        x: [-5.000e-01]
      nit: 2
      jac: [ 0.000e+00]
 hess_inv: [[ 5.000e-01]]
     nfev: 8
     njev: 4

[-0.50000001]


## sparse data:
## data that have mostly unused elements like 0
[1,2,6,0,0,0,0,7,8,0,0,0,0,0,0,0]
## dense array: opposite of sparse data

In [17]:
from scipy.sparse import csr_matrix
import numpy as np
arr = np.array([0,0,0,0,0,2,0,0,1,3,0,4])
print(csr_matrix(arr))

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (1, 12)>
  Coords	Values
  (0, 5)	2
  (0, 8)	1
  (0, 9)	3
  (0, 11)	4


In [21]:
print(csr_matrix(arr).data)
print(csr_matrix(arr).count_nonzero())

[2 1 3 4]
4


In [22]:
arr = np.array([0,0,0,0,0,2,0,0,1,3,0,4])
mat = csr_matrix(arr)
mat.eliminate_zeros()
print(mat)


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (1, 12)>
  Coords	Values
  (0, 5)	2
  (0, 8)	1
  (0, 9)	3
  (0, 11)	4


In [23]:
arr = np.array([0,0,0,0,0,2,0,0,1,3,0,4])
mat = csr_matrix(arr)
mat.sum_duplicates()
print(mat)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (1, 12)>
  Coords	Values
  (0, 5)	2
  (0, 8)	1
  (0, 9)	3
  (0, 11)	4


## graphs to store data
1 connected components
2 djikstra
3 floyd worshall
4 bellman ford
5 depth first order
6 breadth first order

In [25]:
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix
arr = np.array([[1,0,2],[1,0,0],[0,0,2]])
newarr = csr_matrix(arr)
print(connected_components(newarr))

(1, array([0, 0, 0], dtype=int32))


In [26]:
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix
arr = np.array([[1,0,2],[1,0,0],[0,0,2]])
newarr = csr_matrix(arr)
print(dijkstra(newarr,return_predecessors = True,indices = 0))

(array([ 0., inf,  2.]), array([-9999, -9999,     0], dtype=int32))


In [29]:
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix
arr = np.array([[1,0,2],[1,0,0],[0,0,2]])
newarr = csr_matrix(arr)
print(floyd_warshall(newarr,return_predecessors = True))

(array([[ 0., inf,  2.],
       [ 1.,  0.,  3.],
       [inf, inf,  0.]]), array([[-9999, -9999,     0],
       [    1, -9999,     0],
       [-9999, -9999, -9999]], dtype=int32))


In [31]:
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix
arr = np.array([[1,0,2],[1,0,0],[0,0,2]])
newarr = csr_matrix(arr)
print(bellman_ford(newarr,return_predecessors = True,indices = 0))

(array([ 0., inf,  2.]), array([-9999, -9999,     0], dtype=int32))


In [32]:
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix
arr = np.array([[1,0,2],[1,0,0],[0,0,2]])
newarr = csr_matrix(arr)
print(depth_first_order(newarr,1))

(array([1, 0, 2], dtype=int32), array([    1, -9999,     0], dtype=int32))


In [33]:
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix
arr = np.array([[1,0,2],[1,0,0],[0,0,2]])
newarr = csr_matrix(arr)
print(breadth_first_order,(newarr,1))

<cyfunction breadth_first_order at 0x0000022F3B66B440> (<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 3)>, 1)


## distance 
1 euclidean
2 cityblock
3 cosine
4 hamming


In [34]:
from scipy.spatial.distance import euclidean
p1 =(2,6)
p2 = (5,2)
res = euclidean(p1,p2)
print(res)

5.0


In [36]:
from scipy.spatial.distance import cityblock
p1 =(2,6)
p2 = (5,2)
res = cityblock(p1,p2)
print(res)

7


In [37]:
from scipy.spatial.distance import cosine
p1 =(2,6)
p2 = (5,2)
res = cosine(p1,p2)
print(res)

0.35405775853382626


In [39]:
from scipy.spatial.distance import hamming
p1 =(True,False,True,True)
p2 = (False,True,True,False)
res = hamming(p1,p2)
print(res)

0.75
